/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfirmSubscription200Response,
  CreateList201Response,
  CreateListRequest,
  DeletePolicyRule200Response,
  ErrorResponse,
  GetLists200Response,
  GetSubscribers200Response,
  SubscribeRequest,
  UnsubscribeSubscriber200Response,
} from '../models/index';
import {
    ConfirmSubscription200ResponseFromJSON,
    ConfirmSubscription200ResponseToJSON,
    CreateList201ResponseFromJSON,
    CreateList201ResponseToJSON,
    CreateListRequestFromJSON,
    CreateListRequestToJSON,
    DeletePolicyRule200ResponseFromJSON,
    DeletePolicyRule200ResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetLists200ResponseFromJSON,
    GetLists200ResponseToJSON,
    GetSubscribers200ResponseFromJSON,
    GetSubscribers200ResponseToJSON,
    SubscribeRequestFromJSON,
    SubscribeRequestToJSON,
    UnsubscribeSubscriber200ResponseFromJSON,
    UnsubscribeSubscriber200ResponseToJSON,
} from '../models/index';

export interface ConfirmSubscriptionRequest {
    token: string;
}

export interface CreateListOperationRequest {
    createListRequest: CreateListRequest;
}

export interface DeleteListRequest {
    listId: string;
}

export interface GetListRequest {
    listId: string;
}

export interface GetListsRequest {
    page?: number;
    perPage?: number;
}

export interface GetSubscribersRequest {
    listId: string;
    page?: number;
    perPage?: number;
    status?: GetSubscribersStatusEnum;
}

export interface SubscribeOperationRequest {
    listId: string;
    subscribeRequest: SubscribeRequest;
}

export interface UnsubscribeSubscriberRequest {
    listId: string;
    subscriberId: string;
}

/**
 * 
 */
export class SubscriberListsApi extends runtime.BaseAPI {

    /**
     * Confirm a pending subscription via the token sent in the confirmation email. No authentication required. Redirects to the list\'s configured redirect URL if set, otherwise returns JSON. Tokens expire after 72 hours.
     * Confirm subscription
     */
    async confirmSubscriptionRaw(requestParameters: ConfirmSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmSubscription200Response>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling confirmSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/confirm/{token}`;
        urlPath = urlPath.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmSubscription200ResponseFromJSON(jsonValue));
    }

    /**
     * Confirm a pending subscription via the token sent in the confirmation email. No authentication required. Redirects to the list\'s configured redirect URL if set, otherwise returns JSON. Tokens expire after 72 hours.
     * Confirm subscription
     */
    async confirmSubscription(requestParameters: ConfirmSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmSubscription200Response> {
        const response = await this.confirmSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new subscriber list. Use lists to organize subscribers and manage double opt-in confirmation flows.
     * Create a subscriber list
     */
    async createListRaw(requestParameters: CreateListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateList201Response>> {
        if (requestParameters['createListRequest'] == null) {
            throw new runtime.RequiredError(
                'createListRequest',
                'Required parameter "createListRequest" was null or undefined when calling createList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lists`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateListRequestToJSON(requestParameters['createListRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateList201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new subscriber list. Use lists to organize subscribers and manage double opt-in confirmation flows.
     * Create a subscriber list
     */
    async createList(requestParameters: CreateListOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateList201Response> {
        const response = await this.createListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft-delete a subscriber list. Existing subscribers are retained but the list is no longer usable.
     * Delete a subscriber list
     */
    async deleteListRaw(requestParameters: DeleteListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletePolicyRule200Response>> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling deleteList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lists/{list_id}`;
        urlPath = urlPath.replace(`{${"list_id"}}`, encodeURIComponent(String(requestParameters['listId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletePolicyRule200ResponseFromJSON(jsonValue));
    }

    /**
     * Soft-delete a subscriber list. Existing subscribers are retained but the list is no longer usable.
     * Delete a subscriber list
     */
    async deleteList(requestParameters: DeleteListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletePolicyRule200Response> {
        const response = await this.deleteListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of a specific subscriber list including subscriber and confirmed counts.
     * Get a subscriber list
     */
    async getListRaw(requestParameters: GetListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateList201Response>> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling getList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lists/{list_id}`;
        urlPath = urlPath.replace(`{${"list_id"}}`, encodeURIComponent(String(requestParameters['listId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateList201ResponseFromJSON(jsonValue));
    }

    /**
     * Get details of a specific subscriber list including subscriber and confirmed counts.
     * Get a subscriber list
     */
    async getList(requestParameters: GetListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateList201Response> {
        const response = await this.getListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all subscriber lists for the authenticated account with pagination.
     * List subscriber lists
     */
    async getListsRaw(requestParameters: GetListsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetLists200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lists`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetLists200ResponseFromJSON(jsonValue));
    }

    /**
     * List all subscriber lists for the authenticated account with pagination.
     * List subscriber lists
     */
    async getLists(requestParameters: GetListsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetLists200Response> {
        const response = await this.getListsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List paginated subscribers for a specific list. Optionally filter by status.
     * List subscribers
     */
    async getSubscribersRaw(requestParameters: GetSubscribersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSubscribers200Response>> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling getSubscribers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lists/{list_id}/subscribers`;
        urlPath = urlPath.replace(`{${"list_id"}}`, encodeURIComponent(String(requestParameters['listId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSubscribers200ResponseFromJSON(jsonValue));
    }

    /**
     * List paginated subscribers for a specific list. Optionally filter by status.
     * List subscribers
     */
    async getSubscribers(requestParameters: GetSubscribersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSubscribers200Response> {
        const response = await this.getSubscribersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a subscriber to a list and initiate the double opt-in confirmation flow. The subscriber receives a confirmation email and must click the link to confirm. Rate limited to 10 requests/min per IP and 1000/hour per account.
     * Subscribe to a list
     */
    async subscribeRaw(requestParameters: SubscribeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnsubscribeSubscriber200Response>> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling subscribe().'
            );
        }

        if (requestParameters['subscribeRequest'] == null) {
            throw new runtime.RequiredError(
                'subscribeRequest',
                'Required parameter "subscribeRequest" was null or undefined when calling subscribe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/subscribe/{list_id}`;
        urlPath = urlPath.replace(`{${"list_id"}}`, encodeURIComponent(String(requestParameters['listId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscribeRequestToJSON(requestParameters['subscribeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnsubscribeSubscriber200ResponseFromJSON(jsonValue));
    }

    /**
     * Add a subscriber to a list and initiate the double opt-in confirmation flow. The subscriber receives a confirmation email and must click the link to confirm. Rate limited to 10 requests/min per IP and 1000/hour per account.
     * Subscribe to a list
     */
    async subscribe(requestParameters: SubscribeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnsubscribeSubscriber200Response> {
        const response = await this.subscribeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set a subscriber\'s status to unsubscribed. The consent record is retained for compliance.
     * Unsubscribe a subscriber
     */
    async unsubscribeSubscriberRaw(requestParameters: UnsubscribeSubscriberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnsubscribeSubscriber200Response>> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling unsubscribeSubscriber().'
            );
        }

        if (requestParameters['subscriberId'] == null) {
            throw new runtime.RequiredError(
                'subscriberId',
                'Required parameter "subscriberId" was null or undefined when calling unsubscribeSubscriber().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lists/{list_id}/subscribers/{subscriber_id}`;
        urlPath = urlPath.replace(`{${"list_id"}}`, encodeURIComponent(String(requestParameters['listId'])));
        urlPath = urlPath.replace(`{${"subscriber_id"}}`, encodeURIComponent(String(requestParameters['subscriberId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnsubscribeSubscriber200ResponseFromJSON(jsonValue));
    }

    /**
     * Set a subscriber\'s status to unsubscribed. The consent record is retained for compliance.
     * Unsubscribe a subscriber
     */
    async unsubscribeSubscriber(requestParameters: UnsubscribeSubscriberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnsubscribeSubscriber200Response> {
        const response = await this.unsubscribeSubscriberRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetSubscribersStatusEnum = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Unsubscribed: 'unsubscribed',
    Bounced: 'bounced'
} as const;
export type GetSubscribersStatusEnum = typeof GetSubscribersStatusEnum[keyof typeof GetSubscribersStatusEnum];
