/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  HealthCheck200Response,
  TelemetrySummary,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HealthCheck200ResponseFromJSON,
    HealthCheck200ResponseToJSON,
    TelemetrySummaryFromJSON,
    TelemetrySummaryToJSON,
} from '../models/index';

export interface GetTelemetrySummaryRequest {
    window?: GetTelemetrySummaryWindowEnum;
}

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     * Get validation metrics for your account. Useful for building dashboards and monitoring. Supports ETag caching.
     * Get validation telemetry
     */
    async getTelemetrySummaryRaw(requestParameters: GetTelemetrySummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelemetrySummary>> {
        const queryParameters: any = {};

        if (requestParameters['window'] != null) {
            queryParameters['window'] = requestParameters['window'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/telemetry/summary`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TelemetrySummaryFromJSON(jsonValue));
    }

    /**
     * Get validation metrics for your account. Useful for building dashboards and monitoring. Supports ETag caching.
     * Get validation telemetry
     */
    async getTelemetrySummary(requestParameters: GetTelemetrySummaryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelemetrySummary> {
        const response = await this.getTelemetrySummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check API health status. No authentication required.
     * Health check
     */
    async healthCheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthCheck200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheck200ResponseFromJSON(jsonValue));
    }

    /**
     * Check API health status. No authentication required.
     * Health check
     */
    async healthCheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthCheck200Response> {
        const response = await this.healthCheckRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetTelemetrySummaryWindowEnum = {
    _1h: '1h',
    _24h: '24h',
    _30d: '30d'
} as const;
export type GetTelemetrySummaryWindowEnum = typeof GetTelemetrySummaryWindowEnum[keyof typeof GetTelemetrySummaryWindowEnum];
