/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddSuppressionRequestEntriesInner
 */
export interface AddSuppressionRequestEntriesInner {
    /**
     * 
     * @type {string}
     * @memberof AddSuppressionRequestEntriesInner
     */
    type: AddSuppressionRequestEntriesInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AddSuppressionRequestEntriesInner
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof AddSuppressionRequestEntriesInner
     */
    reason?: string;
}


/**
 * @export
 */
export const AddSuppressionRequestEntriesInnerTypeEnum = {
    Email: 'email',
    Domain: 'domain'
} as const;
export type AddSuppressionRequestEntriesInnerTypeEnum = typeof AddSuppressionRequestEntriesInnerTypeEnum[keyof typeof AddSuppressionRequestEntriesInnerTypeEnum];


/**
 * Check if a given object implements the AddSuppressionRequestEntriesInner interface.
 */
export function instanceOfAddSuppressionRequestEntriesInner(value: object): value is AddSuppressionRequestEntriesInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AddSuppressionRequestEntriesInnerFromJSON(json: any): AddSuppressionRequestEntriesInner {
    return AddSuppressionRequestEntriesInnerFromJSONTyped(json, false);
}

export function AddSuppressionRequestEntriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSuppressionRequestEntriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': json['value'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function AddSuppressionRequestEntriesInnerToJSON(json: any): AddSuppressionRequestEntriesInner {
    return AddSuppressionRequestEntriesInnerToJSONTyped(json, false);
}

export function AddSuppressionRequestEntriesInnerToJSONTyped(value?: AddSuppressionRequestEntriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': value['value'],
        'reason': value['reason'],
    };
}

