/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddSuppressionResponse
 */
export interface AddSuppressionResponse {
    /**
     * 
     * @type {string}
     * @memberof AddSuppressionResponse
     */
    schemaVersion?: string;
    /**
     * 
     * @type {number}
     * @memberof AddSuppressionResponse
     */
    added?: number;
    /**
     * 
     * @type {number}
     * @memberof AddSuppressionResponse
     */
    skipped?: number;
}

/**
 * Check if a given object implements the AddSuppressionResponse interface.
 */
export function instanceOfAddSuppressionResponse(value: object): value is AddSuppressionResponse {
    return true;
}

export function AddSuppressionResponseFromJSON(json: any): AddSuppressionResponse {
    return AddSuppressionResponseFromJSONTyped(json, false);
}

export function AddSuppressionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSuppressionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'added': json['added'] == null ? undefined : json['added'],
        'skipped': json['skipped'] == null ? undefined : json['skipped'],
    };
}

export function AddSuppressionResponseToJSON(json: any): AddSuppressionResponse {
    return AddSuppressionResponseToJSONTyped(json, false);
}

export function AddSuppressionResponseToJSONTyped(value?: AddSuppressionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'added': value['added'],
        'skipped': value['skipped'],
    };
}

