/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Delivery routing info (present when status is queued)
 * @export
 * @interface BatchDeliverResponseDelivery
 */
export interface BatchDeliverResponseDelivery {
    /**
     * IP pool used
     * @type {string}
     * @memberof BatchDeliverResponseDelivery
     */
    pool?: string;
    /**
     * Delivery lane (green or yellow)
     * @type {string}
     * @memberof BatchDeliverResponseDelivery
     */
    lane?: string;
    /**
     * Timestamp when batch was queued
     * @type {Date}
     * @memberof BatchDeliverResponseDelivery
     */
    queuedAt?: Date;
}

/**
 * Check if a given object implements the BatchDeliverResponseDelivery interface.
 */
export function instanceOfBatchDeliverResponseDelivery(value: object): value is BatchDeliverResponseDelivery {
    return true;
}

export function BatchDeliverResponseDeliveryFromJSON(json: any): BatchDeliverResponseDelivery {
    return BatchDeliverResponseDeliveryFromJSONTyped(json, false);
}

export function BatchDeliverResponseDeliveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchDeliverResponseDelivery {
    if (json == null) {
        return json;
    }
    return {
        
        'pool': json['pool'] == null ? undefined : json['pool'],
        'lane': json['lane'] == null ? undefined : json['lane'],
        'queuedAt': json['queued_at'] == null ? undefined : (new Date(json['queued_at'])),
    };
}

export function BatchDeliverResponseDeliveryToJSON(json: any): BatchDeliverResponseDelivery {
    return BatchDeliverResponseDeliveryToJSONTyped(json, false);
}

export function BatchDeliverResponseDeliveryToJSONTyped(value?: BatchDeliverResponseDelivery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pool': value['pool'],
        'lane': value['lane'],
        'queued_at': value['queuedAt'] == null ? value['queuedAt'] : value['queuedAt'].toISOString(),
    };
}

