/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchDeliverRequestStructuredData } from './BatchDeliverRequestStructuredData';
import {
    BatchDeliverRequestStructuredDataFromJSON,
    BatchDeliverRequestStructuredDataFromJSONTyped,
    BatchDeliverRequestStructuredDataToJSON,
    BatchDeliverRequestStructuredDataToJSONTyped,
} from './BatchDeliverRequestStructuredData';

/**
 * Same fields as DeliverRequest but 'to' accepts up to 100 recipients.
 * @export
 * @interface BatchDeliverRequest
 */
export interface BatchDeliverRequest {
    /**
     * List of recipient email addresses (max 100)
     * @type {Array<string>}
     * @memberof BatchDeliverRequest
     */
    to: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BatchDeliverRequest
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof BatchDeliverRequest
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof BatchDeliverRequest
     */
    html?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchDeliverRequest
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchDeliverRequest
     */
    domainId: string;
    /**
     * 
     * @type {string}
     * @memberof BatchDeliverRequest
     */
    replyTo?: string;
    /**
     * 
     * @type {object}
     * @memberof BatchDeliverRequest
     */
    headers?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof BatchDeliverRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BatchDeliverRequest
     */
    campaignType?: string;
    /**
     * 
     * @type {BatchDeliverRequestStructuredData}
     * @memberof BatchDeliverRequest
     */
    structuredData?: BatchDeliverRequestStructuredData;
    /**
     * 
     * @type {object}
     * @memberof BatchDeliverRequest
     */
    options?: object;
}

/**
 * Check if a given object implements the BatchDeliverRequest interface.
 */
export function instanceOfBatchDeliverRequest(value: object): value is BatchDeliverRequest {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('domainId' in value) || value['domainId'] === undefined) return false;
    return true;
}

export function BatchDeliverRequestFromJSON(json: any): BatchDeliverRequest {
    return BatchDeliverRequestFromJSONTyped(json, false);
}

export function BatchDeliverRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchDeliverRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'from': json['from'],
        'subject': json['subject'],
        'html': json['html'] == null ? undefined : json['html'],
        'text': json['text'] == null ? undefined : json['text'],
        'domainId': json['domain_id'],
        'replyTo': json['reply_to'] == null ? undefined : json['reply_to'],
        'headers': json['headers'] == null ? undefined : json['headers'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'campaignType': json['campaign_type'] == null ? undefined : json['campaign_type'],
        'structuredData': json['structured_data'] == null ? undefined : BatchDeliverRequestStructuredDataFromJSON(json['structured_data']),
        'options': json['options'] == null ? undefined : json['options'],
    };
}

export function BatchDeliverRequestToJSON(json: any): BatchDeliverRequest {
    return BatchDeliverRequestToJSONTyped(json, false);
}

export function BatchDeliverRequestToJSONTyped(value?: BatchDeliverRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'from': value['from'],
        'subject': value['subject'],
        'html': value['html'],
        'text': value['text'],
        'domain_id': value['domainId'],
        'reply_to': value['replyTo'],
        'headers': value['headers'],
        'tags': value['tags'],
        'campaign_type': value['campaignType'],
        'structured_data': BatchDeliverRequestStructuredDataToJSON(value['structuredData']),
        'options': value['options'],
    };
}

