/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmSubscription200Response
 */
export interface ConfirmSubscription200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmSubscription200Response
     */
    confirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfirmSubscription200Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmSubscription200Response
     */
    listId?: string;
}

/**
 * Check if a given object implements the ConfirmSubscription200Response interface.
 */
export function instanceOfConfirmSubscription200Response(value: object): value is ConfirmSubscription200Response {
    return true;
}

export function ConfirmSubscription200ResponseFromJSON(json: any): ConfirmSubscription200Response {
    return ConfirmSubscription200ResponseFromJSONTyped(json, false);
}

export function ConfirmSubscription200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmSubscription200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'confirmed': json['confirmed'] == null ? undefined : json['confirmed'],
        'email': json['email'] == null ? undefined : json['email'],
        'listId': json['list_id'] == null ? undefined : json['list_id'],
    };
}

export function ConfirmSubscription200ResponseToJSON(json: any): ConfirmSubscription200Response {
    return ConfirmSubscription200ResponseToJSONTyped(json, false);
}

export function ConfirmSubscription200ResponseToJSONTyped(value?: ConfirmSubscription200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'confirmed': value['confirmed'],
        'email': value['email'],
        'list_id': value['listId'],
    };
}

