/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliverResponseDelivery
 */
export interface DeliverResponseDelivery {
    /**
     * IP pool used
     * @type {string}
     * @memberof DeliverResponseDelivery
     */
    pool?: string;
    /**
     * Delivery lane
     * @type {string}
     * @memberof DeliverResponseDelivery
     */
    lane?: string;
    /**
     * Whether warmup throttling was applied
     * @type {boolean}
     * @memberof DeliverResponseDelivery
     */
    warmupLimited?: boolean;
}

/**
 * Check if a given object implements the DeliverResponseDelivery interface.
 */
export function instanceOfDeliverResponseDelivery(value: object): value is DeliverResponseDelivery {
    return true;
}

export function DeliverResponseDeliveryFromJSON(json: any): DeliverResponseDelivery {
    return DeliverResponseDeliveryFromJSONTyped(json, false);
}

export function DeliverResponseDeliveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliverResponseDelivery {
    if (json == null) {
        return json;
    }
    return {
        
        'pool': json['pool'] == null ? undefined : json['pool'],
        'lane': json['lane'] == null ? undefined : json['lane'],
        'warmupLimited': json['warmup_limited'] == null ? undefined : json['warmup_limited'],
    };
}

export function DeliverResponseDeliveryToJSON(json: any): DeliverResponseDelivery {
    return DeliverResponseDeliveryToJSONTyped(json, false);
}

export function DeliverResponseDeliveryToJSONTyped(value?: DeliverResponseDelivery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pool': value['pool'],
        'lane': value['lane'],
        'warmup_limited': value['warmupLimited'],
    };
}

