/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type DeliverRequestStructuredData
 * JSON-LD structured data (object, array, or string). Max 10KB.
 * @export
 */
export type DeliverRequestStructuredData = Array<any> | object | string;

export function DeliverRequestStructuredDataFromJSON(json: any): DeliverRequestStructuredData {
    return DeliverRequestStructuredDataFromJSONTyped(json, false);
}

export function DeliverRequestStructuredDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliverRequestStructuredData {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function DeliverRequestStructuredDataToJSON(json: any): any {
    return DeliverRequestStructuredDataToJSONTyped(json, false);
}

export function DeliverRequestStructuredDataToJSONTyped(value?: DeliverRequestStructuredData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

