/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeliverRequestStructuredData } from './DeliverRequestStructuredData';
import {
    DeliverRequestStructuredDataFromJSON,
    DeliverRequestStructuredDataFromJSONTyped,
    DeliverRequestStructuredDataToJSON,
    DeliverRequestStructuredDataToJSONTyped,
} from './DeliverRequestStructuredData';
import type { DeliverRequestToInner } from './DeliverRequestToInner';
import {
    DeliverRequestToInnerFromJSON,
    DeliverRequestToInnerFromJSONTyped,
    DeliverRequestToInnerToJSON,
    DeliverRequestToInnerToJSONTyped,
} from './DeliverRequestToInner';
import type { DeliverRequestOptions } from './DeliverRequestOptions';
import {
    DeliverRequestOptionsFromJSON,
    DeliverRequestOptionsFromJSONTyped,
    DeliverRequestOptionsToJSON,
    DeliverRequestOptionsToJSONTyped,
} from './DeliverRequestOptions';

/**
 * 
 * @export
 * @interface DeliverRequest
 */
export interface DeliverRequest {
    /**
     * List of recipient email addresses
     * @type {Array<DeliverRequestToInner>}
     * @memberof DeliverRequest
     */
    to: Array<DeliverRequestToInner>;
    /**
     * Sender email address (must match sending domain)
     * @type {string}
     * @memberof DeliverRequest
     */
    from: string;
    /**
     * Email subject line
     * @type {string}
     * @memberof DeliverRequest
     */
    subject: string;
    /**
     * HTML email body
     * @type {string}
     * @memberof DeliverRequest
     */
    html?: string;
    /**
     * Plain text email body
     * @type {string}
     * @memberof DeliverRequest
     */
    text?: string;
    /**
     * Sending domain UUID
     * @type {string}
     * @memberof DeliverRequest
     */
    domainId: string;
    /**
     * Reply-to address
     * @type {string}
     * @memberof DeliverRequest
     */
    replyTo?: string;
    /**
     * Extra email headers
     * @type {object}
     * @memberof DeliverRequest
     */
    headers?: object;
    /**
     * Tags for categorization
     * @type {Array<string>}
     * @memberof DeliverRequest
     */
    tags?: Array<string>;
    /**
     * Campaign type for JSON-LD auto-generation
     * @type {string}
     * @memberof DeliverRequest
     */
    campaignType?: DeliverRequestCampaignTypeEnum;
    /**
     * 
     * @type {DeliverRequestStructuredData}
     * @memberof DeliverRequest
     */
    structuredData?: DeliverRequestStructuredData;
    /**
     * 
     * @type {DeliverRequestOptions}
     * @memberof DeliverRequest
     */
    options?: DeliverRequestOptions;
}


/**
 * @export
 */
export const DeliverRequestCampaignTypeEnum = {
    OrderConfirmation: 'order_confirmation',
    ShippingNotification: 'shipping_notification',
    SubscriptionConfirm: 'subscription_confirm',
    ReviewRequest: 'review_request',
    EventInvitation: 'event_invitation',
    Promotional: 'promotional',
    Welcome: 'welcome',
    PasswordReset: 'password_reset',
    AppointmentReminder: 'appointment_reminder',
    TicketConfirmation: 'ticket_confirmation'
} as const;
export type DeliverRequestCampaignTypeEnum = typeof DeliverRequestCampaignTypeEnum[keyof typeof DeliverRequestCampaignTypeEnum];


/**
 * Check if a given object implements the DeliverRequest interface.
 */
export function instanceOfDeliverRequest(value: object): value is DeliverRequest {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('domainId' in value) || value['domainId'] === undefined) return false;
    return true;
}

export function DeliverRequestFromJSON(json: any): DeliverRequest {
    return DeliverRequestFromJSONTyped(json, false);
}

export function DeliverRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliverRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'to': ((json['to'] as Array<any>).map(DeliverRequestToInnerFromJSON)),
        'from': json['from'],
        'subject': json['subject'],
        'html': json['html'] == null ? undefined : json['html'],
        'text': json['text'] == null ? undefined : json['text'],
        'domainId': json['domain_id'],
        'replyTo': json['reply_to'] == null ? undefined : json['reply_to'],
        'headers': json['headers'] == null ? undefined : json['headers'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'campaignType': json['campaign_type'] == null ? undefined : json['campaign_type'],
        'structuredData': json['structured_data'] == null ? undefined : DeliverRequestStructuredDataFromJSON(json['structured_data']),
        'options': json['options'] == null ? undefined : DeliverRequestOptionsFromJSON(json['options']),
    };
}

export function DeliverRequestToJSON(json: any): DeliverRequest {
    return DeliverRequestToJSONTyped(json, false);
}

export function DeliverRequestToJSONTyped(value?: DeliverRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': ((value['to'] as Array<any>).map(DeliverRequestToInnerToJSON)),
        'from': value['from'],
        'subject': value['subject'],
        'html': value['html'],
        'text': value['text'],
        'domain_id': value['domainId'],
        'reply_to': value['replyTo'],
        'headers': value['headers'],
        'tags': value['tags'],
        'campaign_type': value['campaignType'],
        'structured_data': DeliverRequestStructuredDataToJSON(value['structuredData']),
        'options': DeliverRequestOptionsToJSON(value['options']),
    };
}

