/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSendingStats200ResponseStats
 */
export interface GetSendingStats200ResponseStats {
    /**
     * 
     * @type {string}
     * @memberof GetSendingStats200ResponseStats
     */
    period?: string;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    sent?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    delivered?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    bounced?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    deferred?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    failed?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    openedTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    openedUnique?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    clickedTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    clickedUnique?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    unsubscribed?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    deliveryRate?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    openRate?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    clickRate?: number;
    /**
     * Opens from known bots/scanners
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    botOpens?: number;
    /**
     * Verified human opens
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    humanOpens?: number;
    /**
     * Percentage of opens from bots
     * @type {number}
     * @memberof GetSendingStats200ResponseStats
     */
    botOpenPct?: number;
}

/**
 * Check if a given object implements the GetSendingStats200ResponseStats interface.
 */
export function instanceOfGetSendingStats200ResponseStats(value: object): value is GetSendingStats200ResponseStats {
    return true;
}

export function GetSendingStats200ResponseStatsFromJSON(json: any): GetSendingStats200ResponseStats {
    return GetSendingStats200ResponseStatsFromJSONTyped(json, false);
}

export function GetSendingStats200ResponseStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSendingStats200ResponseStats {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'] == null ? undefined : json['period'],
        'sent': json['sent'] == null ? undefined : json['sent'],
        'delivered': json['delivered'] == null ? undefined : json['delivered'],
        'bounced': json['bounced'] == null ? undefined : json['bounced'],
        'deferred': json['deferred'] == null ? undefined : json['deferred'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'openedTotal': json['opened_total'] == null ? undefined : json['opened_total'],
        'openedUnique': json['opened_unique'] == null ? undefined : json['opened_unique'],
        'clickedTotal': json['clicked_total'] == null ? undefined : json['clicked_total'],
        'clickedUnique': json['clicked_unique'] == null ? undefined : json['clicked_unique'],
        'unsubscribed': json['unsubscribed'] == null ? undefined : json['unsubscribed'],
        'deliveryRate': json['delivery_rate'] == null ? undefined : json['delivery_rate'],
        'openRate': json['open_rate'] == null ? undefined : json['open_rate'],
        'clickRate': json['click_rate'] == null ? undefined : json['click_rate'],
        'botOpens': json['bot_opens'] == null ? undefined : json['bot_opens'],
        'humanOpens': json['human_opens'] == null ? undefined : json['human_opens'],
        'botOpenPct': json['bot_open_pct'] == null ? undefined : json['bot_open_pct'],
    };
}

export function GetSendingStats200ResponseStatsToJSON(json: any): GetSendingStats200ResponseStats {
    return GetSendingStats200ResponseStatsToJSONTyped(json, false);
}

export function GetSendingStats200ResponseStatsToJSONTyped(value?: GetSendingStats200ResponseStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': value['period'],
        'sent': value['sent'],
        'delivered': value['delivered'],
        'bounced': value['bounced'],
        'deferred': value['deferred'],
        'failed': value['failed'],
        'opened_total': value['openedTotal'],
        'opened_unique': value['openedUnique'],
        'clicked_total': value['clickedTotal'],
        'clicked_unique': value['clickedUnique'],
        'unsubscribed': value['unsubscribed'],
        'delivery_rate': value['deliveryRate'],
        'open_rate': value['openRate'],
        'click_rate': value['clickRate'],
        'bot_opens': value['botOpens'],
        'human_opens': value['humanOpens'],
        'bot_open_pct': value['botOpenPct'],
    };
}

