/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSendingStats200ResponseStats } from './GetSendingStats200ResponseStats';
import {
    GetSendingStats200ResponseStatsFromJSON,
    GetSendingStats200ResponseStatsFromJSONTyped,
    GetSendingStats200ResponseStatsToJSON,
    GetSendingStats200ResponseStatsToJSONTyped,
} from './GetSendingStats200ResponseStats';

/**
 * 
 * @export
 * @interface GetSendingStats200Response
 */
export interface GetSendingStats200Response {
    /**
     * 
     * @type {GetSendingStats200ResponseStats}
     * @memberof GetSendingStats200Response
     */
    stats?: GetSendingStats200ResponseStats;
}

/**
 * Check if a given object implements the GetSendingStats200Response interface.
 */
export function instanceOfGetSendingStats200Response(value: object): value is GetSendingStats200Response {
    return true;
}

export function GetSendingStats200ResponseFromJSON(json: any): GetSendingStats200Response {
    return GetSendingStats200ResponseFromJSONTyped(json, false);
}

export function GetSendingStats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSendingStats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'stats': json['stats'] == null ? undefined : GetSendingStats200ResponseStatsFromJSON(json['stats']),
    };
}

export function GetSendingStats200ResponseToJSON(json: any): GetSendingStats200Response {
    return GetSendingStats200ResponseToJSONTyped(json, false);
}

export function GetSendingStats200ResponseToJSONTyped(value?: GetSendingStats200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stats': GetSendingStats200ResponseStatsToJSON(value['stats']),
    };
}

