/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Subscriber } from './Subscriber';
import {
    SubscriberFromJSON,
    SubscriberFromJSONTyped,
    SubscriberToJSON,
    SubscriberToJSONTyped,
} from './Subscriber';

/**
 * 
 * @export
 * @interface GetSubscribers200Response
 */
export interface GetSubscribers200Response {
    /**
     * 
     * @type {Array<Subscriber>}
     * @memberof GetSubscribers200Response
     */
    subscribers?: Array<Subscriber>;
    /**
     * 
     * @type {number}
     * @memberof GetSubscribers200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSubscribers200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSubscribers200Response
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSubscribers200Response
     */
    pages?: number;
}

/**
 * Check if a given object implements the GetSubscribers200Response interface.
 */
export function instanceOfGetSubscribers200Response(value: object): value is GetSubscribers200Response {
    return true;
}

export function GetSubscribers200ResponseFromJSON(json: any): GetSubscribers200Response {
    return GetSubscribers200ResponseFromJSONTyped(json, false);
}

export function GetSubscribers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscribers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'subscribers': json['subscribers'] == null ? undefined : ((json['subscribers'] as Array<any>).map(SubscriberFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'pages': json['pages'] == null ? undefined : json['pages'],
    };
}

export function GetSubscribers200ResponseToJSON(json: any): GetSubscribers200Response {
    return GetSubscribers200ResponseToJSONTyped(json, false);
}

export function GetSubscribers200ResponseToJSONTyped(value?: GetSubscribers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscribers': value['subscribers'] == null ? undefined : ((value['subscribers'] as Array<any>).map(SubscriberToJSON)),
        'total': value['total'],
        'page': value['page'],
        'per_page': value['perPage'],
        'pages': value['pages'],
    };
}

