/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobSummary } from './JobSummary';
import {
    JobSummaryFromJSON,
    JobSummaryFromJSONTyped,
    JobSummaryToJSON,
    JobSummaryToJSONTyped,
} from './JobSummary';

/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    status?: JobStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    processedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    progressPercent?: number;
    /**
     * 
     * @type {JobSummary}
     * @memberof Job
     */
    summary?: JobSummary;
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    completedAt?: Date;
    /**
     * 
     * @type {object}
     * @memberof Job
     */
    metadata?: object;
}


/**
 * @export
 */
export const JobStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type JobStatusEnum = typeof JobStatusEnum[keyof typeof JobStatusEnum];


/**
 * Check if a given object implements the Job interface.
 */
export function instanceOfJob(value: object): value is Job {
    return true;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalCount': json['total_count'] == null ? undefined : json['total_count'],
        'processedCount': json['processed_count'] == null ? undefined : json['processed_count'],
        'progressPercent': json['progress_percent'] == null ? undefined : json['progress_percent'],
        'summary': json['summary'] == null ? undefined : JobSummaryFromJSON(json['summary']),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function JobToJSON(json: any): Job {
    return JobToJSONTyped(json, false);
}

export function JobToJSONTyped(value?: Job | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'total_count': value['totalCount'],
        'processed_count': value['processedCount'],
        'progress_percent': value['progressPercent'],
        'summary': JobSummaryToJSON(value['summary']),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'metadata': value['metadata'],
    };
}

