/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Policy } from './Policy';
import {
    PolicyFromJSON,
    PolicyFromJSONTyped,
    PolicyToJSON,
    PolicyToJSONTyped,
} from './Policy';

/**
 * 
 * @export
 * @interface PolicyResponse
 */
export interface PolicyResponse {
    /**
     * 
     * @type {string}
     * @memberof PolicyResponse
     */
    schemaVersion?: string;
    /**
     * 
     * @type {Policy}
     * @memberof PolicyResponse
     */
    policy?: Policy;
}

/**
 * Check if a given object implements the PolicyResponse interface.
 */
export function instanceOfPolicyResponse(value: object): value is PolicyResponse {
    return true;
}

export function PolicyResponseFromJSON(json: any): PolicyResponse {
    return PolicyResponseFromJSONTyped(json, false);
}

export function PolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'policy': json['policy'] == null ? undefined : PolicyFromJSON(json['policy']),
    };
}

export function PolicyResponseToJSON(json: any): PolicyResponse {
    return PolicyResponseToJSONTyped(json, false);
}

export function PolicyResponseToJSONTyped(value?: PolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'policy': PolicyToJSON(value['policy']),
    };
}

