/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolicyRuleAction } from './PolicyRuleAction';
import {
    PolicyRuleActionFromJSON,
    PolicyRuleActionFromJSONTyped,
    PolicyRuleActionToJSON,
    PolicyRuleActionToJSONTyped,
} from './PolicyRuleAction';

/**
 * 
 * @export
 * @interface PolicyRule
 */
export interface PolicyRule {
    /**
     * 
     * @type {number}
     * @memberof PolicyRule
     */
    id?: number;
    /**
     * Rule type determines how condition is evaluated
     * @type {string}
     * @memberof PolicyRule
     */
    type: PolicyRuleTypeEnum;
    /**
     * Condition depends on rule type. status_override: {status}, domain_filter: {domain_mode, domains}, check_requirement: {check, required}, sub_status_override: {sub_status}
     * @type {object}
     * @memberof PolicyRule
     */
    condition: object;
    /**
     * 
     * @type {PolicyRuleAction}
     * @memberof PolicyRule
     */
    action: PolicyRuleAction;
    /**
     * 
     * @type {number}
     * @memberof PolicyRule
     */
    sequence?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PolicyRule
     */
    isEnabled?: boolean;
}


/**
 * @export
 */
export const PolicyRuleTypeEnum = {
    StatusOverride: 'status_override',
    DomainFilter: 'domain_filter',
    CheckRequirement: 'check_requirement',
    SubStatusOverride: 'sub_status_override'
} as const;
export type PolicyRuleTypeEnum = typeof PolicyRuleTypeEnum[keyof typeof PolicyRuleTypeEnum];


/**
 * Check if a given object implements the PolicyRule interface.
 */
export function instanceOfPolicyRule(value: object): value is PolicyRule {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('condition' in value) || value['condition'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function PolicyRuleFromJSON(json: any): PolicyRule {
    return PolicyRuleFromJSONTyped(json, false);
}

export function PolicyRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyRule {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'],
        'condition': json['condition'],
        'action': PolicyRuleActionFromJSON(json['action']),
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'isEnabled': json['is_enabled'] == null ? undefined : json['is_enabled'],
    };
}

export function PolicyRuleToJSON(json: any): PolicyRule {
    return PolicyRuleToJSONTyped(json, false);
}

export function PolicyRuleToJSONTyped(value?: PolicyRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'condition': value['condition'],
        'action': PolicyRuleActionToJSON(value['action']),
        'sequence': value['sequence'],
        'is_enabled': value['isEnabled'],
    };
}

