/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolicyRule } from './PolicyRule';
import {
    PolicyRuleFromJSON,
    PolicyRuleFromJSONTyped,
    PolicyRuleToJSON,
    PolicyRuleToJSONTyped,
} from './PolicyRule';

/**
 * 
 * @export
 * @interface PolicyPresetsResponsePresetsInner
 */
export interface PolicyPresetsResponsePresetsInner {
    /**
     * 
     * @type {string}
     * @memberof PolicyPresetsResponsePresetsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyPresetsResponsePresetsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyPresetsResponsePresetsInner
     */
    description?: string;
    /**
     * 
     * @type {Array<PolicyRule>}
     * @memberof PolicyPresetsResponsePresetsInner
     */
    rules?: Array<PolicyRule>;
}

/**
 * Check if a given object implements the PolicyPresetsResponsePresetsInner interface.
 */
export function instanceOfPolicyPresetsResponsePresetsInner(value: object): value is PolicyPresetsResponsePresetsInner {
    return true;
}

export function PolicyPresetsResponsePresetsInnerFromJSON(json: any): PolicyPresetsResponsePresetsInner {
    return PolicyPresetsResponsePresetsInnerFromJSONTyped(json, false);
}

export function PolicyPresetsResponsePresetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyPresetsResponsePresetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'rules': json['rules'] == null ? undefined : ((json['rules'] as Array<any>).map(PolicyRuleFromJSON)),
    };
}

export function PolicyPresetsResponsePresetsInnerToJSON(json: any): PolicyPresetsResponsePresetsInner {
    return PolicyPresetsResponsePresetsInnerToJSONTyped(json, false);
}

export function PolicyPresetsResponsePresetsInnerToJSONTyped(value?: PolicyPresetsResponsePresetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'rules': value['rules'] == null ? undefined : ((value['rules'] as Array<any>).map(PolicyRuleToJSON)),
    };
}

