/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolicyRule } from './PolicyRule';
import {
    PolicyRuleFromJSON,
    PolicyRuleFromJSONTyped,
    PolicyRuleToJSON,
    PolicyRuleToJSONTyped,
} from './PolicyRule';

/**
 * 
 * @export
 * @interface Policy
 */
export interface Policy {
    /**
     * 
     * @type {number}
     * @memberof Policy
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Policy
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Policy
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Policy
     */
    isDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Policy
     */
    isEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Policy
     */
    priority?: number;
    /**
     * 
     * @type {number}
     * @memberof Policy
     */
    ruleCount?: number;
    /**
     * 
     * @type {Array<PolicyRule>}
     * @memberof Policy
     */
    rules?: Array<PolicyRule>;
    /**
     * 
     * @type {Date}
     * @memberof Policy
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the Policy interface.
 */
export function instanceOfPolicy(value: object): value is Policy {
    return true;
}

export function PolicyFromJSON(json: any): Policy {
    return PolicyFromJSONTyped(json, false);
}

export function PolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Policy {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'isEnabled': json['is_enabled'] == null ? undefined : json['is_enabled'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'ruleCount': json['rule_count'] == null ? undefined : json['rule_count'],
        'rules': json['rules'] == null ? undefined : ((json['rules'] as Array<any>).map(PolicyRuleFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function PolicyToJSON(json: any): Policy {
    return PolicyToJSONTyped(json, false);
}

export function PolicyToJSONTyped(value?: Policy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'is_default': value['isDefault'],
        'is_enabled': value['isEnabled'],
        'priority': value['priority'],
        'rule_count': value['ruleCount'],
        'rules': value['rules'] == null ? undefined : ((value['rules'] as Array<any>).map(PolicyRuleToJSON)),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

