/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { ValidationResult } from './ValidationResult';
import {
    ValidationResultFromJSON,
    ValidationResultFromJSONTyped,
    ValidationResultToJSON,
    ValidationResultToJSONTyped,
} from './ValidationResult';

/**
 * 
 * @export
 * @interface ResultsResponse
 */
export interface ResultsResponse {
    /**
     * 
     * @type {string}
     * @memberof ResultsResponse
     */
    schemaVersion?: string;
    /**
     * 
     * @type {Array<ValidationResult>}
     * @memberof ResultsResponse
     */
    results?: Array<ValidationResult>;
    /**
     * 
     * @type {Pagination}
     * @memberof ResultsResponse
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ResultsResponse interface.
 */
export function instanceOfResultsResponse(value: object): value is ResultsResponse {
    return true;
}

export function ResultsResponseFromJSON(json: any): ResultsResponse {
    return ResultsResponseFromJSONTyped(json, false);
}

export function ResultsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ValidationResultFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ResultsResponseToJSON(json: any): ResultsResponse {
    return ResultsResponseToJSONTyped(json, false);
}

export function ResultsResponseToJSONTyped(value?: ResultsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ValidationResultToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

