/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendingDomainDnsRecordsNs } from './SendingDomainDnsRecordsNs';
import {
    SendingDomainDnsRecordsNsFromJSON,
    SendingDomainDnsRecordsNsFromJSONTyped,
    SendingDomainDnsRecordsNsToJSON,
    SendingDomainDnsRecordsNsToJSONTyped,
} from './SendingDomainDnsRecordsNs';

/**
 * DNS records for domain verification
 * @export
 * @interface SendingDomainDnsRecords
 */
export interface SendingDomainDnsRecords {
    /**
     * 
     * @type {SendingDomainDnsRecordsNs}
     * @memberof SendingDomainDnsRecords
     */
    ns?: SendingDomainDnsRecordsNs;
}

/**
 * Check if a given object implements the SendingDomainDnsRecords interface.
 */
export function instanceOfSendingDomainDnsRecords(value: object): value is SendingDomainDnsRecords {
    return true;
}

export function SendingDomainDnsRecordsFromJSON(json: any): SendingDomainDnsRecords {
    return SendingDomainDnsRecordsFromJSONTyped(json, false);
}

export function SendingDomainDnsRecordsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendingDomainDnsRecords {
    if (json == null) {
        return json;
    }
    return {
        
        'ns': json['ns'] == null ? undefined : SendingDomainDnsRecordsNsFromJSON(json['ns']),
    };
}

export function SendingDomainDnsRecordsToJSON(json: any): SendingDomainDnsRecords {
    return SendingDomainDnsRecordsToJSONTyped(json, false);
}

export function SendingDomainDnsRecordsToJSONTyped(value?: SendingDomainDnsRecords | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ns': SendingDomainDnsRecordsNsToJSON(value['ns']),
    };
}

