/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriberList
 */
export interface SubscriberList {
    /**
     * List UUID
     * @type {string}
     * @memberof SubscriberList
     */
    id?: string;
    /**
     * Account ID
     * @type {number}
     * @memberof SubscriberList
     */
    accountId?: number;
    /**
     * List name
     * @type {string}
     * @memberof SubscriberList
     */
    name?: string;
    /**
     * List description
     * @type {string}
     * @memberof SubscriberList
     */
    description?: string | null;
    /**
     * Redirect URL after confirmation
     * @type {string}
     * @memberof SubscriberList
     */
    confirmationRedirectUrl?: string | null;
    /**
     * Confirmation email subject
     * @type {string}
     * @memberof SubscriberList
     */
    confirmationSubject?: string | null;
    /**
     * Confirmation email sender name
     * @type {string}
     * @memberof SubscriberList
     */
    confirmationFromName?: string | null;
    /**
     * Total subscriber count
     * @type {number}
     * @memberof SubscriberList
     */
    subscriberCount?: number;
    /**
     * Confirmed subscriber count
     * @type {number}
     * @memberof SubscriberList
     */
    confirmedCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof SubscriberList
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscriberList
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the SubscriberList interface.
 */
export function instanceOfSubscriberList(value: object): value is SubscriberList {
    return true;
}

export function SubscriberListFromJSON(json: any): SubscriberList {
    return SubscriberListFromJSONTyped(json, false);
}

export function SubscriberListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriberList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'confirmationRedirectUrl': json['confirmation_redirect_url'] == null ? undefined : json['confirmation_redirect_url'],
        'confirmationSubject': json['confirmation_subject'] == null ? undefined : json['confirmation_subject'],
        'confirmationFromName': json['confirmation_from_name'] == null ? undefined : json['confirmation_from_name'],
        'subscriberCount': json['subscriber_count'] == null ? undefined : json['subscriber_count'],
        'confirmedCount': json['confirmed_count'] == null ? undefined : json['confirmed_count'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function SubscriberListToJSON(json: any): SubscriberList {
    return SubscriberListToJSONTyped(json, false);
}

export function SubscriberListToJSONTyped(value?: SubscriberList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'account_id': value['accountId'],
        'name': value['name'],
        'description': value['description'],
        'confirmation_redirect_url': value['confirmationRedirectUrl'],
        'confirmation_subject': value['confirmationSubject'],
        'confirmation_from_name': value['confirmationFromName'],
        'subscriber_count': value['subscriberCount'],
        'confirmed_count': value['confirmedCount'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

