/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuppressionEntry
 */
export interface SuppressionEntry {
    /**
     * 
     * @type {number}
     * @memberof SuppressionEntry
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SuppressionEntry
     */
    type?: SuppressionEntryTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SuppressionEntry
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof SuppressionEntry
     */
    reason?: string;
    /**
     * 
     * @type {Date}
     * @memberof SuppressionEntry
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const SuppressionEntryTypeEnum = {
    Email: 'email',
    Domain: 'domain'
} as const;
export type SuppressionEntryTypeEnum = typeof SuppressionEntryTypeEnum[keyof typeof SuppressionEntryTypeEnum];


/**
 * Check if a given object implements the SuppressionEntry interface.
 */
export function instanceOfSuppressionEntry(value: object): value is SuppressionEntry {
    return true;
}

export function SuppressionEntryFromJSON(json: any): SuppressionEntry {
    return SuppressionEntryFromJSONTyped(json, false);
}

export function SuppressionEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuppressionEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function SuppressionEntryToJSON(json: any): SuppressionEntry {
    return SuppressionEntryToJSONTyped(json, false);
}

export function SuppressionEntryToJSONTyped(value?: SuppressionEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'value': value['value'],
        'reason': value['reason'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

