/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuppressionCheckResponse
 */
export interface SuppressionCheckResponse {
    /**
     * 
     * @type {string}
     * @memberof SuppressionCheckResponse
     */
    schemaVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof SuppressionCheckResponse
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SuppressionCheckResponse
     */
    suppressed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SuppressionCheckResponse
     */
    matchType?: SuppressionCheckResponseMatchTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SuppressionCheckResponse
     */
    matchValue?: string;
}


/**
 * @export
 */
export const SuppressionCheckResponseMatchTypeEnum = {
    Email: 'email',
    Domain: 'domain'
} as const;
export type SuppressionCheckResponseMatchTypeEnum = typeof SuppressionCheckResponseMatchTypeEnum[keyof typeof SuppressionCheckResponseMatchTypeEnum];


/**
 * Check if a given object implements the SuppressionCheckResponse interface.
 */
export function instanceOfSuppressionCheckResponse(value: object): value is SuppressionCheckResponse {
    return true;
}

export function SuppressionCheckResponseFromJSON(json: any): SuppressionCheckResponse {
    return SuppressionCheckResponseFromJSONTyped(json, false);
}

export function SuppressionCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuppressionCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'email': json['email'] == null ? undefined : json['email'],
        'suppressed': json['suppressed'] == null ? undefined : json['suppressed'],
        'matchType': json['match_type'] == null ? undefined : json['match_type'],
        'matchValue': json['match_value'] == null ? undefined : json['match_value'],
    };
}

export function SuppressionCheckResponseToJSON(json: any): SuppressionCheckResponse {
    return SuppressionCheckResponseToJSONTyped(json, false);
}

export function SuppressionCheckResponseToJSONTyped(value?: SuppressionCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'email': value['email'],
        'suppressed': value['suppressed'],
        'match_type': value['matchType'],
        'match_value': value['matchValue'],
    };
}

