/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TelemetrySummaryTopReasonsInner
 */
export interface TelemetrySummaryTopReasonsInner {
    /**
     * 
     * @type {string}
     * @memberof TelemetrySummaryTopReasonsInner
     */
    reason?: string;
    /**
     * 
     * @type {number}
     * @memberof TelemetrySummaryTopReasonsInner
     */
    count?: number;
}

/**
 * Check if a given object implements the TelemetrySummaryTopReasonsInner interface.
 */
export function instanceOfTelemetrySummaryTopReasonsInner(value: object): value is TelemetrySummaryTopReasonsInner {
    return true;
}

export function TelemetrySummaryTopReasonsInnerFromJSON(json: any): TelemetrySummaryTopReasonsInner {
    return TelemetrySummaryTopReasonsInnerFromJSONTyped(json, false);
}

export function TelemetrySummaryTopReasonsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelemetrySummaryTopReasonsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function TelemetrySummaryTopReasonsInnerToJSON(json: any): TelemetrySummaryTopReasonsInner {
    return TelemetrySummaryTopReasonsInnerToJSONTyped(json, false);
}

export function TelemetrySummaryTopReasonsInnerToJSONTyped(value?: TelemetrySummaryTopReasonsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'count': value['count'],
    };
}

