/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TelemetrySummaryTopDomainsInner
 */
export interface TelemetrySummaryTopDomainsInner {
    /**
     * 
     * @type {string}
     * @memberof TelemetrySummaryTopDomainsInner
     */
    domain?: string;
    /**
     * 
     * @type {number}
     * @memberof TelemetrySummaryTopDomainsInner
     */
    volume?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetrySummaryTopDomainsInner
     */
    deliverable?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetrySummaryTopDomainsInner
     */
    reject?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetrySummaryTopDomainsInner
     */
    unknown?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetrySummaryTopDomainsInner
     */
    catchAll?: number;
}

/**
 * Check if a given object implements the TelemetrySummaryTopDomainsInner interface.
 */
export function instanceOfTelemetrySummaryTopDomainsInner(value: object): value is TelemetrySummaryTopDomainsInner {
    return true;
}

export function TelemetrySummaryTopDomainsInnerFromJSON(json: any): TelemetrySummaryTopDomainsInner {
    return TelemetrySummaryTopDomainsInnerFromJSONTyped(json, false);
}

export function TelemetrySummaryTopDomainsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelemetrySummaryTopDomainsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'] == null ? undefined : json['domain'],
        'volume': json['volume'] == null ? undefined : json['volume'],
        'deliverable': json['deliverable'] == null ? undefined : json['deliverable'],
        'reject': json['reject'] == null ? undefined : json['reject'],
        'unknown': json['unknown'] == null ? undefined : json['unknown'],
        'catchAll': json['catchAll'] == null ? undefined : json['catchAll'],
    };
}

export function TelemetrySummaryTopDomainsInnerToJSON(json: any): TelemetrySummaryTopDomainsInner {
    return TelemetrySummaryTopDomainsInnerToJSONTyped(json, false);
}

export function TelemetrySummaryTopDomainsInnerToJSONTyped(value?: TelemetrySummaryTopDomainsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'volume': value['volume'],
        'deliverable': value['deliverable'],
        'reject': value['reject'],
        'unknown': value['unknown'],
        'catchAll': value['catchAll'],
    };
}

