/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Mock validation result to test against
 * @export
 * @interface TestPolicyRequestTestResult
 */
export interface TestPolicyRequestTestResult {
    /**
     * 
     * @type {string}
     * @memberof TestPolicyRequestTestResult
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof TestPolicyRequestTestResult
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof TestPolicyRequestTestResult
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof TestPolicyRequestTestResult
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof TestPolicyRequestTestResult
     */
    subStatus?: string;
}

/**
 * Check if a given object implements the TestPolicyRequestTestResult interface.
 */
export function instanceOfTestPolicyRequestTestResult(value: object): value is TestPolicyRequestTestResult {
    return true;
}

export function TestPolicyRequestTestResultFromJSON(json: any): TestPolicyRequestTestResult {
    return TestPolicyRequestTestResultFromJSONTyped(json, false);
}

export function TestPolicyRequestTestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestPolicyRequestTestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'status': json['status'] == null ? undefined : json['status'],
        'action': json['action'] == null ? undefined : json['action'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'subStatus': json['sub_status'] == null ? undefined : json['sub_status'],
    };
}

export function TestPolicyRequestTestResultToJSON(json: any): TestPolicyRequestTestResult {
    return TestPolicyRequestTestResultToJSONTyped(json, false);
}

export function TestPolicyRequestTestResultToJSONTyped(value?: TestPolicyRequestTestResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'status': value['status'],
        'action': value['action'],
        'domain': value['domain'],
        'sub_status': value['subStatus'],
    };
}

