/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Subscriber } from './Subscriber';
import {
    SubscriberFromJSON,
    SubscriberFromJSONTyped,
    SubscriberToJSON,
    SubscriberToJSONTyped,
} from './Subscriber';

/**
 * 
 * @export
 * @interface UnsubscribeSubscriber200Response
 */
export interface UnsubscribeSubscriber200Response {
    /**
     * 
     * @type {Subscriber}
     * @memberof UnsubscribeSubscriber200Response
     */
    subscriber?: Subscriber;
}

/**
 * Check if a given object implements the UnsubscribeSubscriber200Response interface.
 */
export function instanceOfUnsubscribeSubscriber200Response(value: object): value is UnsubscribeSubscriber200Response {
    return true;
}

export function UnsubscribeSubscriber200ResponseFromJSON(json: any): UnsubscribeSubscriber200Response {
    return UnsubscribeSubscriber200ResponseFromJSONTyped(json, false);
}

export function UnsubscribeSubscriber200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsubscribeSubscriber200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriber': json['subscriber'] == null ? undefined : SubscriberFromJSON(json['subscriber']),
    };
}

export function UnsubscribeSubscriber200ResponseToJSON(json: any): UnsubscribeSubscriber200Response {
    return UnsubscribeSubscriber200ResponseToJSONTyped(json, false);
}

export function UnsubscribeSubscriber200ResponseToJSONTyped(value?: UnsubscribeSubscriber200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriber': SubscriberToJSON(value['subscriber']),
    };
}

