/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Present when a validation policy modified the result.
 * @export
 * @interface ValidationResponsePolicyApplied
 */
export interface ValidationResponsePolicyApplied {
    /**
     * 
     * @type {number}
     * @memberof ValidationResponsePolicyApplied
     */
    policyId?: number;
    /**
     * 
     * @type {string}
     * @memberof ValidationResponsePolicyApplied
     */
    policyName?: string;
    /**
     * 
     * @type {number}
     * @memberof ValidationResponsePolicyApplied
     */
    ruleId?: number;
    /**
     * 
     * @type {string}
     * @memberof ValidationResponsePolicyApplied
     */
    ruleType?: string;
}

/**
 * Check if a given object implements the ValidationResponsePolicyApplied interface.
 */
export function instanceOfValidationResponsePolicyApplied(value: object): value is ValidationResponsePolicyApplied {
    return true;
}

export function ValidationResponsePolicyAppliedFromJSON(json: any): ValidationResponsePolicyApplied {
    return ValidationResponsePolicyAppliedFromJSONTyped(json, false);
}

export function ValidationResponsePolicyAppliedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationResponsePolicyApplied {
    if (json == null) {
        return json;
    }
    return {
        
        'policyId': json['policy_id'] == null ? undefined : json['policy_id'],
        'policyName': json['policy_name'] == null ? undefined : json['policy_name'],
        'ruleId': json['rule_id'] == null ? undefined : json['rule_id'],
        'ruleType': json['rule_type'] == null ? undefined : json['rule_type'],
    };
}

export function ValidationResponsePolicyAppliedToJSON(json: any): ValidationResponsePolicyApplied {
    return ValidationResponsePolicyAppliedToJSONTyped(json, false);
}

export function ValidationResponsePolicyAppliedToJSONTyped(value?: ValidationResponsePolicyApplied | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'policy_id': value['policyId'],
        'policy_name': value['policyName'],
        'rule_id': value['ruleId'],
        'rule_type': value['ruleType'],
    };
}

