/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationResponse } from './ValidationResponse';
import {
    ValidationResponseFromJSON,
    ValidationResponseFromJSONTyped,
    ValidationResponseToJSON,
    ValidationResponseToJSONTyped,
} from './ValidationResponse';
import type { ValidateBatch200ResponseSummary } from './ValidateBatch200ResponseSummary';
import {
    ValidateBatch200ResponseSummaryFromJSON,
    ValidateBatch200ResponseSummaryFromJSONTyped,
    ValidateBatch200ResponseSummaryToJSON,
    ValidateBatch200ResponseSummaryToJSONTyped,
} from './ValidateBatch200ResponseSummary';

/**
 * 
 * @export
 * @interface ValidateBatch200Response
 */
export interface ValidateBatch200Response {
    /**
     * 
     * @type {string}
     * @memberof ValidateBatch200Response
     */
    schemaVersion?: string;
    /**
     * 
     * @type {number}
     * @memberof ValidateBatch200Response
     */
    total?: number;
    /**
     * 
     * @type {ValidateBatch200ResponseSummary}
     * @memberof ValidateBatch200Response
     */
    summary?: ValidateBatch200ResponseSummary;
    /**
     * 
     * @type {Array<ValidationResponse>}
     * @memberof ValidateBatch200Response
     */
    results?: Array<ValidationResponse>;
}

/**
 * Check if a given object implements the ValidateBatch200Response interface.
 */
export function instanceOfValidateBatch200Response(value: object): value is ValidateBatch200Response {
    return true;
}

export function ValidateBatch200ResponseFromJSON(json: any): ValidateBatch200Response {
    return ValidateBatch200ResponseFromJSONTyped(json, false);
}

export function ValidateBatch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateBatch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'total': json['total'] == null ? undefined : json['total'],
        'summary': json['summary'] == null ? undefined : ValidateBatch200ResponseSummaryFromJSON(json['summary']),
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ValidationResponseFromJSON)),
    };
}

export function ValidateBatch200ResponseToJSON(json: any): ValidateBatch200Response {
    return ValidateBatch200ResponseToJSONTyped(json, false);
}

export function ValidateBatch200ResponseToJSONTyped(value?: ValidateBatch200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'total': value['total'],
        'summary': ValidateBatch200ResponseSummaryToJSON(value['summary']),
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ValidationResponseToJSON)),
    };
}

