/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationResponseSuppressionMatch } from './ValidationResponseSuppressionMatch';
import {
    ValidationResponseSuppressionMatchFromJSON,
    ValidationResponseSuppressionMatchFromJSONTyped,
    ValidationResponseSuppressionMatchToJSON,
    ValidationResponseSuppressionMatchToJSONTyped,
} from './ValidationResponseSuppressionMatch';
import type { ValidationResponsePolicyApplied } from './ValidationResponsePolicyApplied';
import {
    ValidationResponsePolicyAppliedFromJSON,
    ValidationResponsePolicyAppliedFromJSONTyped,
    ValidationResponsePolicyAppliedToJSON,
    ValidationResponsePolicyAppliedToJSONTyped,
} from './ValidationResponsePolicyApplied';

/**
 * Flat validation response. Conditional fields are omitted (not null) when not applicable.
 * @export
 * @interface ValidationResponse
 */
export interface ValidationResponse {
    /**
     * 
     * @type {string}
     * @memberof ValidationResponse
     */
    schemaVersion: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationResponse
     */
    email: string;
    /**
     * Validation status
     * @type {string}
     * @memberof ValidationResponse
     */
    status: ValidationResponseStatusEnum;
    /**
     * Recommended action
     * @type {string}
     * @memberof ValidationResponse
     */
    action: ValidationResponseActionEnum;
    /**
     * Detailed status reason. Omitted when none.
     * @type {string}
     * @memberof ValidationResponse
     */
    subStatus?: ValidationResponseSubStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidationResponse
     */
    domain: string;
    /**
     * Whether MX records were found for the domain
     * @type {boolean}
     * @memberof ValidationResponse
     */
    mxFound: boolean;
    /**
     * Primary MX hostname. Omitted when MX not resolved.
     * @type {string}
     * @memberof ValidationResponse
     */
    mxHost?: string;
    /**
     * Whether SMTP verification passed. Omitted when SMTP not checked.
     * @type {boolean}
     * @memberof ValidationResponse
     */
    smtpCheck?: boolean;
    /**
     * Whether domain is catch-all. Omitted when SMTP not checked.
     * @type {boolean}
     * @memberof ValidationResponse
     */
    catchAll?: boolean;
    /**
     * Whether domain is a known disposable email provider
     * @type {boolean}
     * @memberof ValidationResponse
     */
    disposable: boolean;
    /**
     * Whether address is a role account (e.g., info@, admin@)
     * @type {boolean}
     * @memberof ValidationResponse
     */
    roleAccount: boolean;
    /**
     * Whether domain is a known free email provider (e.g., gmail.com)
     * @type {boolean}
     * @memberof ValidationResponse
     */
    freeProvider: boolean;
    /**
     * Validation depth used for this check
     * @type {string}
     * @memberof ValidationResponse
     */
    depth: ValidationResponseDepthEnum;
    /**
     * ISO 8601 timestamp of validation
     * @type {Date}
     * @memberof ValidationResponse
     */
    processedAt: Date;
    /**
     * Typo correction suggestion. Omitted when no typo detected.
     * @type {string}
     * @memberof ValidationResponse
     */
    suggestedEmail?: string;
    /**
     * Suggested retry delay in milliseconds. Present only for retry_later action.
     * @type {number}
     * @memberof ValidationResponse
     */
    retryAfterMs?: number;
    /**
     * 
     * @type {ValidationResponseSuppressionMatch}
     * @memberof ValidationResponse
     */
    suppressionMatch?: ValidationResponseSuppressionMatch;
    /**
     * 
     * @type {ValidationResponsePolicyApplied}
     * @memberof ValidationResponse
     */
    policyApplied?: ValidationResponsePolicyApplied;
}


/**
 * @export
 */
export const ValidationResponseStatusEnum = {
    Valid: 'valid',
    Invalid: 'invalid',
    CatchAll: 'catch_all',
    DoNotMail: 'do_not_mail',
    Unknown: 'unknown'
} as const;
export type ValidationResponseStatusEnum = typeof ValidationResponseStatusEnum[keyof typeof ValidationResponseStatusEnum];

/**
 * @export
 */
export const ValidationResponseActionEnum = {
    Accept: 'accept',
    AcceptWithCaution: 'accept_with_caution',
    Reject: 'reject',
    RetryLater: 'retry_later'
} as const;
export type ValidationResponseActionEnum = typeof ValidationResponseActionEnum[keyof typeof ValidationResponseActionEnum];

/**
 * @export
 */
export const ValidationResponseSubStatusEnum = {
    FormatInvalid: 'format_invalid',
    MxMissing: 'mx_missing',
    MxTimeout: 'mx_timeout',
    SmtpUnreachable: 'smtp_unreachable',
    SmtpRejected: 'smtp_rejected',
    Disposable: 'disposable',
    RoleAccount: 'role_account',
    Greylisted: 'greylisted',
    CatchAllDetected: 'catch_all_detected',
    SuppressionMatch: 'suppression_match'
} as const;
export type ValidationResponseSubStatusEnum = typeof ValidationResponseSubStatusEnum[keyof typeof ValidationResponseSubStatusEnum];

/**
 * @export
 */
export const ValidationResponseDepthEnum = {
    Standard: 'standard',
    Enhanced: 'enhanced'
} as const;
export type ValidationResponseDepthEnum = typeof ValidationResponseDepthEnum[keyof typeof ValidationResponseDepthEnum];


/**
 * Check if a given object implements the ValidationResponse interface.
 */
export function instanceOfValidationResponse(value: object): value is ValidationResponse {
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('mxFound' in value) || value['mxFound'] === undefined) return false;
    if (!('disposable' in value) || value['disposable'] === undefined) return false;
    if (!('roleAccount' in value) || value['roleAccount'] === undefined) return false;
    if (!('freeProvider' in value) || value['freeProvider'] === undefined) return false;
    if (!('depth' in value) || value['depth'] === undefined) return false;
    if (!('processedAt' in value) || value['processedAt'] === undefined) return false;
    return true;
}

export function ValidationResponseFromJSON(json: any): ValidationResponse {
    return ValidationResponseFromJSONTyped(json, false);
}

export function ValidationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'],
        'email': json['email'],
        'status': json['status'],
        'action': json['action'],
        'subStatus': json['sub_status'] == null ? undefined : json['sub_status'],
        'domain': json['domain'],
        'mxFound': json['mx_found'],
        'mxHost': json['mx_host'] == null ? undefined : json['mx_host'],
        'smtpCheck': json['smtp_check'] == null ? undefined : json['smtp_check'],
        'catchAll': json['catch_all'] == null ? undefined : json['catch_all'],
        'disposable': json['disposable'],
        'roleAccount': json['role_account'],
        'freeProvider': json['free_provider'],
        'depth': json['depth'],
        'processedAt': (new Date(json['processed_at'])),
        'suggestedEmail': json['suggested_email'] == null ? undefined : json['suggested_email'],
        'retryAfterMs': json['retry_after_ms'] == null ? undefined : json['retry_after_ms'],
        'suppressionMatch': json['suppression_match'] == null ? undefined : ValidationResponseSuppressionMatchFromJSON(json['suppression_match']),
        'policyApplied': json['policy_applied'] == null ? undefined : ValidationResponsePolicyAppliedFromJSON(json['policy_applied']),
    };
}

export function ValidationResponseToJSON(json: any): ValidationResponse {
    return ValidationResponseToJSONTyped(json, false);
}

export function ValidationResponseToJSONTyped(value?: ValidationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'email': value['email'],
        'status': value['status'],
        'action': value['action'],
        'sub_status': value['subStatus'],
        'domain': value['domain'],
        'mx_found': value['mxFound'],
        'mx_host': value['mxHost'],
        'smtp_check': value['smtpCheck'],
        'catch_all': value['catchAll'],
        'disposable': value['disposable'],
        'role_account': value['roleAccount'],
        'free_provider': value['freeProvider'],
        'depth': value['depth'],
        'processed_at': value['processedAt'].toISOString(),
        'suggested_email': value['suggestedEmail'],
        'retry_after_ms': value['retryAfterMs'],
        'suppression_match': ValidationResponseSuppressionMatchToJSON(value['suppressionMatch']),
        'policy_applied': ValidationResponsePolicyAppliedToJSON(value['policyApplied']),
    };
}

