/* tslint:disable */
/* eslint-disable */
/**
 * MailOdds Email Validation API
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationResponseSuppressionMatch } from './ValidationResponseSuppressionMatch';
import {
    ValidationResponseSuppressionMatchFromJSON,
    ValidationResponseSuppressionMatchFromJSONTyped,
    ValidationResponseSuppressionMatchToJSON,
    ValidationResponseSuppressionMatchToJSONTyped,
} from './ValidationResponseSuppressionMatch';

/**
 * 
 * @export
 * @interface ValidationResponse
 */
export interface ValidationResponse {
    /**
     * 
     * @type {string}
     * @memberof ValidationResponse
     */
    schemaVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationResponse
     */
    email: string;
    /**
     * Validation status
     * @type {string}
     * @memberof ValidationResponse
     */
    status: ValidationResponseStatusEnum;
    /**
     * Detailed status reason
     * @type {string}
     * @memberof ValidationResponse
     */
    subStatus?: string;
    /**
     * Recommended action
     * @type {string}
     * @memberof ValidationResponse
     */
    action: ValidationResponseActionEnum;
    /**
     * 
     * @type {string}
     * @memberof ValidationResponse
     */
    domain?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ValidationResponse
     */
    mxFound?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ValidationResponse
     */
    smtpCheck?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ValidationResponse
     */
    disposable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ValidationResponse
     */
    roleAccount?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ValidationResponse
     */
    freeProvider?: boolean;
    /**
     * 
     * @type {ValidationResponseSuppressionMatch}
     * @memberof ValidationResponse
     */
    suppressionMatch?: ValidationResponseSuppressionMatch;
}


/**
 * @export
 */
export const ValidationResponseStatusEnum = {
    Valid: 'valid',
    Invalid: 'invalid',
    DoNotMail: 'do_not_mail',
    Unknown: 'unknown'
} as const;
export type ValidationResponseStatusEnum = typeof ValidationResponseStatusEnum[keyof typeof ValidationResponseStatusEnum];

/**
 * @export
 */
export const ValidationResponseActionEnum = {
    SafeToSend: 'safe_to_send',
    DoNotSend: 'do_not_send',
    ManualReview: 'manual_review'
} as const;
export type ValidationResponseActionEnum = typeof ValidationResponseActionEnum[keyof typeof ValidationResponseActionEnum];


/**
 * Check if a given object implements the ValidationResponse interface.
 */
export function instanceOfValidationResponse(value: object): value is ValidationResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function ValidationResponseFromJSON(json: any): ValidationResponse {
    return ValidationResponseFromJSONTyped(json, false);
}

export function ValidationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'email': json['email'],
        'status': json['status'],
        'subStatus': json['sub_status'] == null ? undefined : json['sub_status'],
        'action': json['action'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'mxFound': json['mx_found'] == null ? undefined : json['mx_found'],
        'smtpCheck': json['smtp_check'] == null ? undefined : json['smtp_check'],
        'disposable': json['disposable'] == null ? undefined : json['disposable'],
        'roleAccount': json['role_account'] == null ? undefined : json['role_account'],
        'freeProvider': json['free_provider'] == null ? undefined : json['free_provider'],
        'suppressionMatch': json['suppression_match'] == null ? undefined : ValidationResponseSuppressionMatchFromJSON(json['suppression_match']),
    };
}

export function ValidationResponseToJSON(json: any): ValidationResponse {
    return ValidationResponseToJSONTyped(json, false);
}

export function ValidationResponseToJSONTyped(value?: ValidationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'email': value['email'],
        'status': value['status'],
        'sub_status': value['subStatus'],
        'action': value['action'],
        'domain': value['domain'],
        'mx_found': value['mxFound'],
        'smtp_check': value['smtpCheck'],
        'disposable': value['disposable'],
        'role_account': value['roleAccount'],
        'free_provider': value['freeProvider'],
        'suppression_match': ValidationResponseSuppressionMatchToJSON(value['suppressionMatch']),
    };
}

